language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t antoniovmonge/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true antoniovmonge/frontend npm run test

